### ISSUE TITLE
#includes not supported in IDL 

### ISSUE THREAD

**Issue by bshantam97** [foxglove/omgidl#138]
**Description**

- Version: omgidl-parser/v1.0.3
- Platform: Ubuntu 22.04

**Steps To Reproduce**
Create an IDL file this is dependent on another IDL file. Include the contents of the other IDL file using #include<Examples.idl>.

**Expected Behavior**
The parser recognizes the defined structures in the other idl.

**Comment by defunctzombie** [comment]
Please provide a failing example of the inputs you provided to this library that did not work.

**Comment by snosenzo** [comment]
@bshantam97  This is intentional. This repo is only aimed to support the mcap's specification of these schemas. [ros2idl](https://mcap.dev/spec/registry#ros2idl) and [omgidl](https://mcap.dev/spec/registry#omgidl) for reference. These specifications require `#include` statements to already be resolved before being used. It's also not feasible for us to support resolving those include statements in a browser context.

I realize that this is not made clear in the readme on the front page of this repo, but I will update it to clarify. Let me know if you have any other questions and thank you for bringing this up.
